### PR TITLE
docker-shell now starts in working directory /pwd

### PR DESCRIPTION
**Pull request by chrisvander**
# Description

Updates `docker-shell` to include the `-w "/pwd"` flag so that, once the container opens, the user has the directory contents right in front of them without needing to add an additional `cd`.

# Type of changes

- [x] A helper script
- [ ] A link to an external resource like a blog post or video
- [ ] Text cleanups/updates

# Checklist

- [x] All new and existing tests pass.
- [x] Any scripts added use `#!/usr/bin/env interpreter` instead of potentially platform-specific direct paths (`#!/bin/sh` is the only exception)
- [x] Scripts are marked executable
- [x] Scripts _do not_ have a language file extension unless they are meant to be sourced and not run standalone. No one should have to know if a script was written in bash, python, ruby or whatever. Not including file extensions makes it easier to rewrite the script in another language later without having to change every reference to the previous version.
- [x] I have added a credit line to README.md for the script
- [x] If there was no author credit in a script added in this PR, I have added one.
- [x] I have confirmed that the link(s) in my PR are valid.

# License Acceptance

- [x] This repository is Apache version 2.0 licensed (some scripts may have alternate licensing inline in their code) and by making this PR, I am contributing my changes to the repository under the terms of the Apache 2 license.

### CODE REVIEW

**Review by unixorn — APPROVED** [review]
lgtm

**Comment by unixorn** [comment]
Please sign-off on your commits - instructions are in the DCO github action's details link.

**Comment by chrisvander** [comment]
Signed off!

**Comment by unixorn** [comment]
Thanks, merging!

**Pull request merged**
